export const localization = {
  ua: {
    flag: false,
    login: 'Логін',
    username: 'Нікнейм',
    password: 'Пароль',
    register: 'Реєстрація',
    name: 'Ім`я',
    email: 'Імейл',
    create_account: 'Створити аккаунт',
    create_car: 'Створити автомобіль',
    car_title: 'Назва автомобіля',
    car_width: 'Ширина автомобіля',
    car_length: 'Довжина автомобіля',
    car_height: 'Висота автомобіля',
    car_seats: 'Кількість місць',
    car_drive_unit: 'Тип приводу автомобіля',
    front: 'Передній',
    rear: 'Задній',
    all_wheel: 'Всі колеса',
    car_class: 'Клас автомобіля',
    car_transmission: 'Тип трансміссії автомобіля',
    mechanics: 'Механічна',
    auto: 'Автоматична',
    car_body: 'Тип кузова автомобіля',
    sedan: 'Седан',
    hatchback: 'Хетчбек',
    universal: 'Універсальний',
    liftback: 'Ліфтбек',
    coupe: 'Купе',
    cabriolet: 'Кабріолет',
    coadster: 'Родстер',
    targa: 'Тарга',
    limousine: 'Лімузин',
    stretch: 'Розтягнутий',
    suv: 'Позашляховик',
    crossover: 'Кросовер',
    pickup: 'Пікап',
    van: 'Ван',
    minivan: 'Мінівен',
    minibus: 'Мікроавтобус',
    bus: 'Автобус',
    car_cost: 'Вартість автомобіля',
    update: 'Оновити',
    car_feedback: 'Зворотній зв\'язок',
    no_feedbacks: 'Немає зворотного зв\'язку.',
    car_comments: 'Коментарі автомобіля',
    no_comments: 'Немає коментарів.',
    car_device_data: 'Дані пристрою автомобіля',
    car_temperature: 'Температура автомобіля',
    car_humidity: 'Вологість автомобіля',
    car_pressure: 'Тиск автомобіля',
    add: 'Додати',
    rent_start: 'Дата початку оренди',
    rent_end: 'Дата закінчення оренди',
    rent: 'Орендувати',
    user_rents: 'Оренда користувача',
    no_rents: 'Немає оренд',
    cars_list: 'Список автомобілів',
    no_cars: 'Немає автомобілів',
    comment: 'Коментувати',
    user_info: 'Інформація користувача',
    first_name: 'Ім`я',
    last_name: 'Прізвище',
    warnings_list: 'Перелік попереджень',
    no_warnings: 'Немає попереджень',
    profile_data: 'Дані профілю',
    environment_preferences: 'Уподобання навколишнього середовища',
    car_preferences: 'Автомобільні уподобання',
    min_cost: 'Мінімальна вартість',
    max_cost: 'Максимальна вартість',
    home: 'Головна',
    cars: 'Автомобілі',
    list: 'Список',
    suggestions: 'Пропозиції',
    rents: 'Оренда',
    weather_map: 'Карта погоди',
    user: 'Користувач',
    user_data: 'Дані користувача',
    logout: 'Вийти',
  },
  en: {
    flag: true,
    login: 'Login',
    username: 'Username',
    password: 'Password',
    register: 'Register',
    name: 'Name',
    email: 'Email',
    create_account: 'Create Account',
    create_car: 'Create Car',
    car_title: 'Car title',
    car_width: 'Car width',
    car_length: 'Car length',
    car_height: 'Car height',
    car_seats: 'Car seats',
    car_drive_unit: 'Car drive unit type',
    front: 'Front',
    rear: 'Rear',
    all_wheel: 'All-wheel',
    car_class: 'Car class type',
    car_transmission: 'Car transmission type',
    mechanics: 'Mechanics',
    auto: 'Auto',
    car_body: 'Car body type',
    sedan: 'Sedan',
    hatchback: 'Hatchback',
    universal: 'Universal',
    liftback: 'Liftback',
    coupe: 'Coupe',
    cabriolet: 'Cabriolet',
    coadster: 'Roadster',
    targa: 'Targa',
    limousine: 'Limousine',
    stretch: 'Stretch',
    suv: 'SUV',
    crossover: 'Crossover',
    pickup: 'Pickup',
    van: 'Van',
    minivan: 'Minivan',
    minibus: 'Minibus',
    bus: 'Bus',
    car_cost: 'Car cost',
    update: 'Update',
    car_feedback: 'Car feedback',
    no_feedbacks: 'No feedbacks.',
    car_comments: 'Car comments',
    no_comments: 'No comments.',
    car_device_data: 'Car device data',
    car_temperature: 'Car temperature',
    car_pressure: 'Car pressure',
    car_humidity: 'Car humidity',
    add: 'Add',
    rent_start: 'Date of rent starting',
    rent_end: 'Date of rent ending',
    rent: 'Rent',
    user_rents: 'User rents',
    no_rents: 'No rents',
    cars_list: 'Cars list',
    no_cars: 'No cars',
    comment: 'Comment',
    user_info: 'User info',
    first_name: 'First name',
    last_name: 'Last name',
    warnings_list: 'Warnings list',
    no_warnings: 'No warnings',
    profile_data: 'Profile data',
    environment_preferences: 'Environment preferences',
    car_preferences: 'Car preferences',
    min_cost: 'Min cost',
    max_cost: 'Max cost',
    home: 'Home',
    cars: 'Cars',
    list: 'List',
    suggestions: 'Suggestions',
    rents: 'Rents',
    weather_map: 'Weather map',
    user: 'User',
    user_data: 'User data',
    logout: 'Logout',
  }
};
