export const localization = {
  ua: {
    flag: false,
    username: "Нікнейм",
    register: "Реєстрація",
    login: "Вхід",
    logout: "Вихів",
    yourProfile: "Ваш Профайл",
    yourProjects: "Ваші Проекти",
    yourHistory: "Ваша Історія",
    user: "Користувач",
    home: "Головна",
    newProject: "Новий проект",
    firstName: "Ім'я",
    lastName: "Прізвизе",
    email: "Email",
    save: "Зберегти",
    cancel: "Відмінити",
    edit: "Редагувати",
    remove: "Видалити",
    yourNote: "Ваша помітка",
    notes: "Помітки",
    submit: "Надіслати",
    newNote: "Новий помітка",
    yourMessage: "Ваше повідомлення",
    download: "Зберегти",
    imageVersions: "Версії зображення",
    yourProject: "Ваш проект",
    projectTitle: "Назва проекту",
    version: "Версія",
    password: "Пароль",
    colorizedFile: "колоризація файлу виконана в",
    savedFile: "зберігання файлу виконана в",
    loggedIn: "зайшли в",
    signedUp: "зареєструвалися в",
    updatedProfile: "оновили профіль в",
    addedNote: "додали помітку в",
    deletedNote: "видалили помітку в",
    noData: "Немає даних",
    you: "Ви",
    semiAutomaticColorization: "Напівавтоматична колоризація",
    diplomaTopic: "Добрий день! Цей проект - моя дипломноа робота з теми",
    topic: "\"Веб-орієнтована система напівавтоматичної колоризації монохромних зображень в градаціях сірого кольору\"",
    workAllows: "Ця робота дозволяє вам",
    firstAllow: "Розфарбовувати зображення в градаціях сірого кольору",
    secondAllow: "Переглядати власних відредагованих зображень",
    thirdAllow: "Переглянути власну історію на цьому веб-сайті",
    fourthAllow: "Переглядати версії своїх зображень",
    fifthAllow: "Редагувати власні зображення",
  },
  en: {
    flag: true,
    username: "Username",
    register: "Register",
    login: "Login",
    logout: "Logout",
    yourProfile: "Your Profile",
    yourProjects: "Your Projects",
    yourHistory: "Your History",
    user: "User",
    home: "Home",
    newProject: "New Project",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    remove: "Remove",
    yourNote: "Your note",
    notes: "Notes",
    submit: "Submit",
    newNote: "New note",
    yourMessage: "Your message",
    download: "Download",
    imageVersions: "Image versions",
    yourProject: "Your project",
    projectTitle: "Project title",
    version: "Version",
    password: "Password",
    colorizedFile: "has colorized file at",
    savedFile: "has saved file at",
    loggedIn: "has logged in at",
    signedUp: "has signed up at",
    updatedProfile: "has updated profile at",
    addedNote: "has added note at",
    deletedNote: "has deleted note at",
    noData: "No data",
    you: "You",
    semiAutomaticColorization: "Semi-automatic colorization",
    diplomaTopic: "Hello! This is a project for my diploma work on the topic",
    topic: "\"Web-oriented system for semi-automatic colorization of monochrome images in grayscale\"",
    workAllows: "This work allows you",
    firstAllow: "Colorize grayscale images",
    secondAllow: "View own edited images",
    thirdAllow: "View own history on this web-site",
    fourthAllow: "View versions of your images",
    fifthAllow: "Edit own images",
  }
};
